version: '3.8'

services:
  # --- DATABASES ---
  db-auth:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    volumes:
      - auth_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d auth_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - micro-network

  db-kanban:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kanban_db
    volumes:
      - kanban_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d kanban_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - micro-network

  db-mail:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mail_db
    volumes:
      - mail_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mail_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - micro-network

  db-note:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: note_db
    volumes:
      - note_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d note_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - micro-network

  db-catechize:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catechize_db
    volumes:
      - catechize_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d catechize_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - micro-network

  # --- MICROSERVICES ---

  auth-service:
    image: ${DOCKERHUB_USERNAME}/auth-service:latest
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://user:password@db-auth:5432/auth_db?sslmode=disable
    depends_on:
      db-auth:
        condition: service_healthy
    networks:
      - micro-network
    env_file:
      - ./env/auth.env

  kanban-service:
    image: ${DOCKERHUB_USERNAME}/kanban-service:latest
    ports:
      - "8081:8081"
    environment:
      DB_URL: postgres://user:password@db-kanban:5432/kanban_db?sslmode=disable
    depends_on:
      db-kanban:
        condition: service_healthy
    networks:
      - micro-network
    env_file:
      - ./env/kanban.env

  mail-service:
    image: ${DOCKERHUB_USERNAME}/mail-service:latest
    ports:
      - "8082:8082"
      - "25:25"
    environment:
      DB_URL: postgres://user:password@db-mail:5432/mail_db?sslmode=disable
    depends_on:
      db-mail:
        condition: service_healthy
    networks:
      - micro-network
    env_file:
      - ./env/mail.env

  note-service:
    image: ${DOCKERHUB_USERNAME}/notes-service:latest
    ports:
      - "8083:8083"
    environment:
      DB_URL: postgres://user:password@db-note:5432/note_db?sslmode=disable
    depends_on:
      db-note:
        condition: service_healthy
    networks:
      - micro-network
    env_file:
      - ./env/notes.env

  catechize-service:
    image: ${DOCKERHUB_USERNAME}/catechize-service:latest
    ports:
      - "8084:8084"
    environment:
      DB_URL: postgres://user:password@db-catechize:5432/catechize_db?sslmode=disable
    depends_on:
      db-catechize:
        condition: service_healthy
    networks:
      - micro-network
    env_file:
      - ./env/catechize.env
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - micro-network
    depends_on:
      - auth-service
      - kanban-service
      - mail-service
      - note-service
      - catechize-service

networks:
  micro-network:
    driver: bridge

volumes:
  auth_data:
  kanban_data:
  mail_data:
  note_data:
  catechize_data:
