services:
  # --- MICROSERVICES ---
  kanban-service:
    image: ${DOCKERHUB_USERNAME}/kanban-service:latest
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanban.rule=PathPrefix(`/api/v1/trello`)"
      - "traefik.http.services.kanban.loadbalancer.server.port=8080"
    networks:
      - micro-network
    env_file:
      - .env

networks:
  micro-network:
    driver: bridge
