services:
  # --- MICROSERVICES ---
  kanban-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanban-service
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanban.rule=PathPrefix(`/api/v1/trello`)"
      - "traefik.http.services.kanban.loadbalancer.server.port=8081"
    ports: 
      - "8080:8080"
    networks:
      - dev-network
    env_file:
      - .env

networks:
  dev-network:
    external: true
