name: CI/CD Microservices (Local Build)

on:
  push:
    branches: [ main ]

jobs:
  deploy-local:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Environment
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
          echo "TUNNEL_TOKEN=${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}" >> .env

      - name: Create env files
        run: |
          mkdir -p env
          echo "${{ secrets.CATECHIZE_ENV_DATA }}" > env/catechize.env
          echo "${{ secrets.AUTH_ENV_DATA }}" > env/auth.env
          echo "${{ secrets.KANBAN_ENV_DATA }}" > env/kanban.env
          echo "${{ secrets.MAIL_ENV_DATA }}" > env/mail.env
          echo "${{ secrets.NOTES_ENV_DATA }}" > env/notes.env

      - name: Build and Deploy Local
        run: |
          docker compose -f docker-compose.prod.yml up -d --build --remove-orphans
          
      - name: Cleanup
        run: |
          docker image prune -f

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.workflow }} report:
            
            Status: ${{ job.status == 'success' && '✅ Success' || '❌ Failed' }}
            Commit: ${{ github.event.head_commit.message }}
            Author: ${{ github.actor }}